version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: maraton-web:latest   # nombre de imagen local; Portainer la construirá
    depends_on:
      - db
    ports:
      - "8081:80"                  # expone Apache en el puerto 80 del host en 8081
    environment:
      # Variables que use tu código PHP para conectarse a la BD
      DB_HOST: db
      DB_NAME: maraton_db
      DB_USER: maraton_user
      DB_PASS: maraton_pass
    restart: always
    networks:
      - webnet

  db:
    image: mysql:8.0
    container_name: mi-maraton-db
    restart: always
    environment:
      # Credenciales y base de datos inicial
      MYSQL_ROOT_PASSWORD: root_pass_seguro
      MYSQL_DATABASE: maraton_db
      MYSQL_USER: maraton_user
      MYSQL_PASSWORD: maraton_pass
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      # Indicarle a phpMyAdmin cómo conectarse al servicio de MySQL
      PMA_HOST: db
      PMA_PORT: 3306
      # Opcional: si quieres preconfigurar usuario y contraseña para login automático
      # PMA_USER: root
      # PMA_PASSWORD: root_pass_seguro
      #
      # Si omites PMA_USER/PMA_PASSWORD, phpMyAdmin mostrará la pantalla de login
      # y debes introducir credenciales (por ejemplo root/root_pass_seguro o maraton_user/maraton_pass).
    ports:
      - "8082:80"                 # expone phpMyAdmin en el puerto 8082 del host
    networks:
      - webnet

volumes:
  dbdata:

networks:
  webnet:
    driver: bridge
